config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end

  resources :doses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_attachment :photo

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :cocktail_id, scope: [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :cocktails
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    @doses = @cocktail.doses
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
    @dose = Dose.new
    @doses = @cocktail.doses
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :photo)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:show, :edit, :update, :destroy]

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @dose.ingredient = Ingredient.find(dose_params[:ingredient_id])
    @dose.description = dose_params[:description]
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose.destroy
    redirect_to dose_path
  end

  private

   def set_dose
      @dose = Dose.find(params[:id])
   end

    def dose_params
      params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
    end
end

# class ReviewsController < ApplicationController
#   before_action :set_restaurant, only: [:create, :new]
#   def new
#     @restaurant = Restaurant.find(params[:restaurant_id])
#     @review = Review.new
#   end

#   def create
#     @review = @restaurant.reviews.new(review_params)
#     # we need `restaurant_id` to asssociate review with corresponding restaurant
#     if @review.save
#       redirect_to restaurant_path(@restaurant)
#     else
#       render :new
#     end
#   end

#   private

#   def review_params
#     params.require(:review).permit(:content, :rating)
#   end

#   def set_restaurant
#     @restaurant = Restaurant.find(params[:restaurant_id])
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-input">
  <%= f.input :photo, as: :attachinary %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="cards">

 <% @cocktails.each do |cocktail| %>
 <div class="card">
<div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.path, height: 300, width: 400, crop: :fill if cocktail.photo %>');">
 <!--  <div class="card-category">Popular</div> -->
  <div class="card-category">
    <span><%= cocktail.name%></span>
    </div>
    <!-- <ol><% cocktail.doses.each do |dose| %></ol>
      <li><%= dose.ingredient.name %></li>
      <% end %> -->


</div>
<div class="card-footer">
<%= link_to "#{image_tag("zoom.png", size: "22x22")}".html_safe, cocktail_path(cocktail) %>
</div>


</div>
<% end %>
</div>
</div>

<div style="text-align: center">
<%= link_to 'New Cocktail', new_cocktail_path, class: "btn-yours" %>
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="wrapper">
    <div>
    <h2 class="title"><%= @cocktail.name %></h2>
    </div>
    <div class="recipe">
      <%= link_to "#{image_tag("add.png", size: "22x22")}".html_safe, new_cocktail_dose_path(@cocktail) %> |
      <%= link_to "#{image_tag("edit.ico", size: "22x22")}".html_safe, edit_cocktail_path(@cocktail) %> |
      <%= link_to "#{image_tag("back.png", size: "22x22")}".html_safe, cocktails_path %>
    </div>
  </div>

  <div class="wrapper">
    <div>
  <% if @cocktail.photo? %>
  <%= cl_image_tag @cocktail.photo.path, width: 400, height: 600, crop: :fill %>
<% end %>
    </div>
    <div class="recipe">
      <strong>Recipe:</strong>
  <ol><% @doses.each do |dose| %>
    <li><%= dose.ingredient.name %>: <%= dose.description %></li>
    <% end %>
  </ol>
    </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :ingredient_id, collection: Ingredient.all %>
  </div>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<%= render 'form', dose: @dose %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
     <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/shared/_footer.html.erb
 <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "COCKTAILS LIST", root_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "logo.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>